# Generated by Django 2.1.1 on 2018-10-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pic_upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='style',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='类别'),
        ),
    ]
